language: python
sudo: false
python:
  - "3.8"
install:
  # Setup bikeshed. See https://tabatkins.github.io/bikeshed/#install-linux
  - pip3 install bikeshed
  - bikeshed update
script:
  - bash ./compile.sh
deploy:
  provider: pages
  edge: true
  skip-cleanup: true
  github-token: $GITHUB_DEPLOY_TOKEN
  keep-history: true
  on:
    branch: master
