language: python
sudo: false
python:
  - "3.8"
before_install:
  - openssl aes-256-cbc -K $encrypted_189e52c2c347_key -iv $encrypted_189e52c2c347_iv -in deploy_key.enc -out deploy_key -d
install:
  # Setup bikeshed. See https://tabatkins.github.io/bikeshed/#install-linux
  - pip3 install bikeshed
  - bikeshed update
script:
  - bash ./compile.sh
deploy:
  provider: pages
  edge: true
  skip-cleanup: true
  deploy_key: deploy_key
  keep-history: true
  on:
    branch: master
